// **** Array of fish objects ****//

var fish = [
  { source: "images/atlantic-cod.jpg", name: "Atlantic Cod", color: "#a08548" },
  { source: "images/blue-marlin.jpg", name: "Blue Marlin", color: "#4863a0" },
  { source: "images/cobia.jpg", name: "Cobia", color: "#a08548" },
  { source: "images/great-barracuda.jpg", name: "Great Barracuda", color: "#63a048" },
  { source: "images/hardhead-catfish.jpg", name: "Hardhead Catfish", color: "#63a048" },
  { source: "images/sailfish.jpg", name: "Sailfish", color: "#4863a0" },
  { source: "images/spotted-tilapia.jpg", name: "Spotted Tilapia", color: "#a08548" },
  { source: "images/striped-anchovy.jpg", name: "Stripped Anchovy", color: "#C0C0C0" },
  { source: "images/red-drum.jpg", name: "Red-Drum", color: "#a04863" },
  { source: "images/atlantic-croaker.jpg", name: "Atlantic Croaker", color: "#63a048" },
  { source: "images/silver-perch.jpg", name: "Silver Perch", color: "#63a048" },
  { source: "images/spotted-sea-trout.jpg", name: "Spotted Sea Trout", color: "#63a048" },
  { source: "images/dolphin-fish.jpg", name: "Dolphin Fish", color: "#4863a0" },
  { source: "images/southern-flounder.jpg", name: "Southern Flounder", color: "#a08548" },
  { source: "images/white-grunt.jpg", name: "White Grunt", color: "#a08548" },
  { source: "images/red-grouper.jpg", name: "Red Grouper", color: "#a04863" },
  { source: "images/black-sea-bass.jpg", name: "Black Sea Bass", color: "#a08548" },
  { source: "images/greater-amberjack.jpg", name: "Greater Amberjack", color: "#a08548" },
  { source: "images/spanish-mackerel.jpg", name: "Spanish Mackerel", color: "#63a058" },
  { source: "images/striped-mullet.jpg", name: "Striped Mullet", color: "#63a058" },
  { source: "images/bull-shark.jpg", name: "Bull Shark", color: "#C0C0C0" },
  { source: "images/blacktip-shark.jpg", name: "Blacktip Shark", color: "#a08548" },
  { source: "images/white-shark.jpg", name: "White Shark", color: "#C0C0C0" },
  { source: "images/great-hammerhead.jpg", name: "Great Hammerhead Shark", color: "#a08548" },
  { source: "images/bullseye-snakehead.jpg", name: "Bullseye Snakehead", color: "#a08548" },
  { source: "images/red-snapper.jpg", name: "Red Snapper", color: "#a04863" },
  { source: "images/Atlantic-stingray.jpg", name: "Atlantic Stingray", color: "#a08548" },
  { source: "images/swordfish.jpg", name: "Swordfish", color: "#a08548" },
  { source: "images/tarpon.jpg", name: "Tarpon", color: "#63a058" },
  { source: "images/gray-triggerfish.jpg", name: "Gray Triggerfish", color: "#a08548" },
  { source: "images/atlantic-tripletail.jpg", name: "Atlantic Tripletail", color: "#a08548" },
  { source: "images/blackfin-tuna.jpg", name: "Blackfin Tuna", color: "#4863a0" }
];
